version: '3'

services:
  back:
    build:
      context: backend
      args:
        - UID=${UID}
        - GID=${GID}
    ports:
      - 10021:8080
    volumes:
      - ./backend/src:/var/www/html
      - ./backend/docker/default.conf:/etc/nginx/conf.d/default.conf

  front:
    build: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    user: "${UID}:${GID}"
    env_file:
      - .env
    ports:
      - 10020:3000
    command: bun run dev